import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Fira_Sans } from "next/font/google";
import { ThemeProvider } from "./_components/theme-providers";
import { cn } from "@/lib/utils";
import "./globals.css";

const fontHeading = Fira_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: "600",
});

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "The next dev",
  description: "Generated by create next app",
  keywords: ["Next.js"],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
